### ISSUE TITLE
Logged in user uploads photo

### ISSUE THREAD

**Issue by PlanetEfficacy** [danbroadbent/turing_photoshare#6]
As a logged in user
When I visit '/'
And I click upload
Then the path is '/photos/new'

As a logged in user
When I visit '/photos/new'
And I click 'Select File'
And I select a file through my web browser's file browser
And I enter a title
And I enter a description
And I select albums
And I click submit
Then the current path is '/photos/:id'
And I see my newly uploaded photo

**Comment by calaway** [comment]
As a logged in user
When I visit '/'
And I click upload
Then the path is '/photos/new'

As a logged in user
When I visit '/photos/new'
And I click 'Select File'
And I select a file through my web browser's file browser
And I enter a title
And I enter a description
And I select albums
And I click submit
Then the current path is '/photos/:id'
And I see my newly uploaded photo
