### ISSUE TITLE
Logged in user visits albums page

### ISSUE THREAD

**Issue by PlanetEfficacy** [danbroadbent/turing_photoshare#7]
As a logged in user
That has albums already created
When I visit '/'
And I click 'You'
And I click 'Albums'
Then the current page is '/:user_id/albums'
And I see all my albums

Alternate navigation:
As a logged in user
That has albums already created
When I visit '/'
And I hover over 'You'
And I click 'Albums'
Then the current page is '/:user_id/albums'

**Comment by calaway** [comment]
How do you guys like this user story style? In particular I'm writing one for each different navigation option. They would go in the same test file, but would be different tests.

**Comment by PlanetEfficacy** [comment]
I really like the detail. I prefer the second one from a usability perspective.

**Comment by calaway** [comment]
My idea is to use both of them. On Flickr there are two different ways to navigate to Albums, so I wrote two user stories, one for each navigation route. Is that cool?

**Comment by PlanetEfficacy** [comment]
Ah, I see. Looks good!
